language: node_js
node_js: "0.10"
sudo: false

before_install:
# https://docs.travis-ci.com/user/installing-dependencies/
- echo 'install beanstalkd'
- apt-get update -qq
- apt-get install beanstalkd
- echo 'installed beanstalkd'
- echo 'starting queue'
- bin/start-queue.sh &
- jobs -l