language: node_js
node_js: "0.10"

before_install:
- echo 'install beanstalkd'
- sudo apt-get update -qq
- sudo apt-get install beanstalkd
- echo 'installed beanstalkd'
- echo 'starting queue'
- bin/start-queue.sh &
- jobs -l