language: node_js
sudo: false
node_js:
  - "node"
  - "6"

addons:
  apt:
    packages:
    - beanstalkd

env:
  - TEST_CMD=test
  - TEST_CMD=run integration-test
script: npm $TEST_CMD

before_install:
# https://docs.travis-ci.com/user/installing-dependencies/
#- echo 'install beanstalkd'
#- apt-get update -qq
#- apt-get install beanstalkd
#- echo 'installed beanstalkd'
- echo 'starting queue'
- bin/start-queue.sh &
- jobs -l
